name: StandingTimer
options:
  bundleIdPrefix: com.nathanhabib
  deploymentTarget:
    macOS: "13.0"
targets:
  StandingTimer:
    type: application
    platform: macOS
    sources: [StandingTimer]
    info:
      path: StandingTimer/Info.plist
      properties:
        LSUIElement: YES
        CFBundleDisplayName: StandingTimer
    settings:
      base:
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.nathanhabib.StandingTimer
